CREATE SEQUENCE SEQ_EMPLOYEE INCREMENT BY 1 MINVALUE 1 MAXVALUE 9999999999999999999999999999 NOCYCLE CACHE 20 NOORDER;

CREATE TABLE EMPLOYEE
(
    EMPLOYEE_ID NUMBER DEFAULT SEQ_EMPLOYEE.NEXTVAL,
    NAME        VARCHAR2(50) NOT NULL,
    PHONE       VARCHAR2(50) NOT NULL,
    EMAIL       VARCHAR2(50) NOT NULL,
    GENDER      VARCHAR2(50) NOT NULL,
    STATUS      VARCHAR2(50) NOT NULL,
    CREATE_DATE DATE NOT NULL,
    CONSTRAINT EMPLOYEE_PK PRIMARY KEY (EMPLOYEE_ID),
    CONSTRAINT EMPLOYEE_UN_PHONE UNIQUE (PHONE),
    CONSTRAINT EMPLOYEE_UN_EMAIL UNIQUE (EMAIL)
);